set(GIT_REF 3dff475f60e33d6275ebbd3f2a637aa7fea078b4)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO drescherjm/simple_vcpkg_library
    REF ${GIT_REF} # or use a specific tag/commit
    SHA512 2d98c3b2fa6108e2b87dad7f51d5e18d789fd9ebca32f199df08a6bd15fa87d3ef35717041e6ded283a70d7a40115eb066f9721a5471d8cc8f2e75ccba94e800 # Replace with the actual sha512 generated by vcpkg hash
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
)

vcpkg_cmake_install()